services:
  - type: web
    name: smart-attendance-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: smart_attendance

  - type: web
    name: smart-attendance-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://smart-attendance-backend.onrender.com
